### ISSUE TITLE
absence version 1.14.2 of Popbill API SpringBoot SDK

### ISSUE THREAD

**Issue by namhokim** [linkhub-sdk/popbill.springboot#1]
- There is no version 1.14.2 of Popbill API SpringBoot SDK
<img width="1397" alt="ScreenShot 2024-03-30 21 46 01" src="https://github.com/linkhub-sdk/popbill.springboot/assets/1442538/75100900-b908-4f43-9052-5cca9c68fa50">

- reference: https://mvnrepository.com/artifact/kr.co.linkhub/popbill-spring-boot-starter
<img width="663" alt="ScreenShot 2024-03-30 21 42 41" src="https://github.com/linkhub-sdk/popbill.springboot/assets/1442538/a31b151c-e73f-4592-9c6d-e0e821c44c74">

- But readme document showed below:
<img width="729" alt="ScreenShot 2024-03-30 21 43 38" src="https://github.com/linkhub-sdk/popbill.springboot/assets/1442538/96000b9c-b4c3-4397-b2c4-432e75fb191c">

Can you fix version of document?

**Comment by raphael-namo** [comment]
1.14.2 버전에서 문자메시지 전송시 실패하는 것을 확인했습니다.

전송시 사용한 메서드는 아래와 같습니다.

- com.popbill.api.MessageService#sendXMS(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, com.popbill.api.message.Message[], java.util.Date, java.lang.Boolean, java.lang.String, java.lang.String)

**Comment by namhokim** [comment]
> 1.14.2 버전에서 문자메시지 전송시 실패하는 것을 확인했습니다.
> 
> 전송시 사용한 메서드는 아래와 같습니다.
> 
> * com.popbill.api.MessageService#sendXMS(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, com.popbill.api.message.Message[], java.util.Date, java.lang.Boolean, java.lang.String, java.lang.String)

#2 에서 원인 및 해결 방안을 제안합니다.

**Comment by namhokim** [comment]
1.14.5 버전 릴리스에 따라 업데이트 되었으므로 본 이슈를 닫습니다.
